// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import java.util.concurrent.ThreadPoolExecutor.DiscardOldestPolicy;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.motorcontrol.MotorController;
import edu.wpi.first.wpilibj.motorcontrol.PWMVictorSPX;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
    import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class Belt extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private AnalogInput beltBottomSensor;
private WPI_VictorSPX victorSPXBelt;
private PWMVictorSPX beltMotor;
private AnalogInput beltSensor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final Double  DISTANCE_TOLERANCE = 2.0;    
    /**
    *
    */
    public Belt() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
beltMotor = new PWMVictorSPX(6);
 addChild("beltMotor",beltMotor);
 beltMotor.setInverted(false);


beltSensor = new AnalogInput(0);
 addChild("beltSensor", beltSensor);
 


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run
        //voltage_scale_factor allows us to compensate for differences in supply voltage.

        double voltage_scale_factor = 5/beltBottomSensor.getVoltage();
        double currentDistanceCentimeters = beltBottomSensor.getValue() * voltage_scale_factor * 0.125;

        double currentDistanceInches = beltBottomSensor.getValue() * voltage_scale_factor * 0.0492;
        SmartDashboard.putNumber("conveyorSensorValue",beltBottomSensor.getValue());
        SmartDashboard.putNumber("conveyorSensorValue",beltSensor.getValue());
        SmartDashboard.putBoolean("conveyorSensorTriggered", isBallInConveyor());
        SmartDashboard.putNumber("currentDistanceInches", currentDistanceInches);
        SmartDashboard.putNumber("currentDistanceCentimeters", currentDistanceCentimeters);
        SmartDashboard.putNumber("votage", beltBottomSensor.getVoltage());
        SmartDashboard.putNumber("scaleFactor", voltage_scale_factor);
    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    public void beltStartUp() {
        beltMotor.set(.5);
    }

    public void beltStartDown() {
        beltMotor.set(-.5);
    }
    public void beltStop() {
        beltMotor.set(0);
    }
    public boolean  isBallInConveyor() {
        if  (beltSensor.getValue() < DISTANCE_TOLERANCE) return true;
        else return false;
    }
    public void test() {
        if(isBallInConveyor())
            beltMotor.set(0);
    }
}
//We're gonna want the belt to only run forwards whenever the shooter is up to speed and aimed properererly, and only allow reverse movements when the intake is clear.
