// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

// ***********************************************************************************************
// * 2/28/2022 Remove all AUTO-GENERATE COMMENTS
// ***********************************************************************************************

package frc.robot.commands;

import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.Constants;
import frc.robot.subsystems.RearShooter;

/**
 *
 */
public class RearFlywheelUpSpeed extends CommandBase {

    private final RearShooter m_rearShooter;
    private Constants.ShootingConstants.ShootingPosition m_position;

    public RearFlywheelUpSpeed(RearShooter subsystem, Constants.ShootingConstants.ShootingPosition position) {
        m_rearShooter = subsystem;
        addRequirements(m_rearShooter);

        m_position = position;
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        m_rearShooter.rearflywheelUpSpeed(m_position);
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
        // m_rearShooter.rearShooterStop();
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        //return m_rearShooter.isFlywheelAtVelocity();
        return true;
    }

    @Override
    public boolean runsWhenDisabled() {
        return false;
    }
}
