// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.Robot;
import frc.robot.RobotContainer;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.Turret;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class TurretAutoAim extends CommandBase {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
        private final Turret m_turret;
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private boolean turretMoving;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS


    public TurretAutoAim(Turret subsystem) {


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        m_turret = subsystem;
        addRequirements(m_turret);
        turretMoving = false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        RobotContainer.getInstance().forceLEDOn();
        m_turret.turretStartLeft();
        turretMoving = true;
        //if (RobotContainer.getInstance().getTv()) m_turret.turretStartLeft();
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        if (RobotContainer.getInstance().getTv() == 1){
            //pretty much done, stop motors, and run pid command to center
            
            ///end(false);
            
        }
       //else m_turret.turretStartLeft();
        
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
        m_turret.turretStop();
        // *** Leave on for AutoCenter *** RobotContainer.getInstance().forceLEDOff();
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
            //if the target is found, then stop, if not found: then check the left limit switch, if left limit switch is hit, move to the right, if the right limit switch is hit, move to the left.
            if (RobotContainer.getInstance().getTv() == 1){
                //pretty much done, stop motors, and run pid command to center
                m_turret.turretStop();
                return true;
            }
           else{
                if(turretMoving){
                    if (m_turret.isLeftLimit())  m_turret.turretStartRight(); 
                    else{
                         if (m_turret.isRightLimit())  m_turret.turretStartLeft();
                    }
                    return false;
                }else{
                    m_turret.turretStartLeft();
                    turretMoving = true;
                    return false;
                }
               
            }
            
            
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
